"""
Core configuration module
"""

from .api_patterns import COMMON_API_PATHS, RESTFUL_SUFFIXES, FUZZ_SUFFIXES, PATH_FRAGMENTS
from .scanner_patterns import (
    API_SPEC_PATTERNS,
    API_ROOT_BLACK_LIST,
    API_ROOT_BLACK_LIST_DURING_SPIDER,
    URL_BLACK_LIST,
    PATH_BLACK_PREFIX,
    PATH_BLACK_KEYWORDS,
    PATH_BLACK_PATTERNS,
    VUE_ROUTER_DIRS,
    DANGER_API_LIST,
    RESPONSE_BLACK_TEXT,
    CONTENT_TYPE_LIST,
    STATIC_FILE_EXT_BLACK_LIST,
    URL_EXT_BLACK_LIST,
)

__all__ = [
    'COMMON_API_PATHS', 
    'RESTFUL_SUFFIXES', 
    'FUZZ_SUFFIXES', 
    'PATH_FRAGMENTS',
    'API_SPEC_PATTERNS',
    'API_ROOT_BLACK_LIST',
    'API_ROOT_BLACK_LIST_DURING_SPIDER',
    'URL_BLACK_LIST',
    'PATH_BLACK_PREFIX',
    'PATH_BLACK_KEYWORDS',
    'PATH_BLACK_PATTERNS',
    'VUE_ROUTER_DIRS',
    'DANGER_API_LIST',
    'RESPONSE_BLACK_TEXT',
    'CONTENT_TYPE_LIST',
    'STATIC_FILE_EXT_BLACK_LIST',
    'URL_EXT_BLACK_LIST',
]
