"""
API 路径模式配置
包含 COMMON_API_PATHS、RESTFUL_SUFFIXES、FUZZ_SUFFIXES 等大列表
从 engine.py 迁移而来
"""

COMMON_API_PATHS = [
    'add', 'ls', 'focus', 'calc', 'download', 'bind', 'execute',
    'logininfo', 'create', 'decrypt', 'new', 'update', 'click',
    'shell', 'export', 'menu', 'retrieve', 'on', 'message', 'admin',
    'calculate', 'append', 'check', 'crypt', 'rename', 'exec', 'detail',
    'clone', 'query', 'verify', 'is', 'authenticate', 'move', 'toggle',
    'make', 'modify', 'upload', 'help', 'demo', 'with', 'alert', 'mode',
    'gen', 'msg', 'edit', 'vrfy', 'enable', 'run', 'open', 'post',
    'proxy', 'subtract', 'initiate', 'read', 'encrypt', 'auth', 'snd',
    'view', 'save', 'config', 'get', 'alter', 'forceLogout', 'build',
    'list', 'show', 'online', 'test', 'pull', 'notice', 'change',
    'put', 'to', 'status', 'search', 'mod', '0', 'send', 'load',
    'login', 'logout', 'register', 'info', 'detail', 'delete', 'remove',
    'insert', 'select', 'update', 'user', 'users', 'order', 'orders',
    'product', 'products', 'goods', 'item', 'items', 'category', 'cart',
    'shop', 'payment', 'account', 'profile', 'setting', 'settings',
    'dashboard', 'home', 'index', 'about', 'contact', 'service',
    'news', 'article', 'blog', 'comment', 'file', 'files', 'upload',
    'download', 'image', 'images', 'video', 'videos', 'audio',
]

RESTFUL_SUFFIXES = [
    '', '/', '/list', '/page', '/all', '/count', '/total', '/sum',
    '/add', '/create', '/new', '/edit', '/update', '/modify', '/save', '/saveOrUpdate',
    '/delete', '/remove', '/del', '/batch', '/batchAdd', '/batchUpdate', '/batchDelete', '/batchCreate', '/batchEdit',
    '/detail', '/detail', '/info', '/get', '/getInfo', '/getDetail', '/getList', '/getAll', '/getPage', '/getById', '/getByCode', '/getByName',
    '/show', '/find', '/fetch', '/fetchAll', '/fetchOne', '/load', '/loadOne', '/retrieve',
    '/enable', '/disable', '/toggle', '/status', '/state', '/state', '/active', '/inactive', '/activate', '/deactivate',
    '/config', '/configuration', '/settings', '/preferences', '/params', '/param', '/setting',
    '/export', '/exportExcel', '/exportCsv', '/exportPdf', '/exportJson', '/import', '/importExcel', '/importCsv', '/upload', '/download',
    '/search', '/query', '/filter', '/sort', '/order', '/page', '/pagination', '/paginate', '/pageData', '/pageSize', '/pageNum',
    '/listJsonData', '/listData', '/listAll', '/listJson', '/listPage', '/json', '/xml', '/tree', '/treeData', '/treeList', '/treeJson',
    '/options', '/select', '/selectById', '/combo', '/combobox', '/autocomplete', '/suggest', '/lookup',
    '/submit', '/reset', '/init', '/initialize', '/refresh', '/reload', '/sync', '/merge', '/synchronize',
    '/login', '/logout', '/register', '/signup', '/signin', '/signout', '/resetPwd', '/forgotPwd', '/resetPassword', '/forgotPassword', '/changePassword', '/updatePassword',
    '/auth', '/authorize', '/authorization', '/token', '/refreshToken', '/accessToken', '/verify', '/validate', '/validation', '/captcha', '/verification', '/verifyEmail', '/verifyPhone',
    '/menu', '/nav', '/navigation', '/sidebar', '/routes', '/permissions', '/access', '/permission', '/permissions', '/perms', '/role', '/roles', '/roleId', '/roleName', '/roleCode',
    '/user', '/users', '/userList', '/userInfo', '/userPage', '/userDetail', '/profile', '/account', '/current', '/own', '/userName', '/userId',
    '/dashboard', '/home', '/index', '/welcome', '/main', '/console', '/workspace', '/portal',
    '/log', '/logs', '/logging', '/audit', '/history', '/record', '/records', '/track', '/trail', '/trace', '/debug', '/loginLog', '/operationLog', '/accessLog', '/errorLog', '/systemLog',
    '/stat', '/stats', '/statistics', '/stats', '/analytics', '/report', '/reports', '/summary', '/overview', '/dashboard',
    '/dict', '/dicts', '/dictionary', '/enum', '/enums', '/constants', '/configs', '/configList', '/systemConfig',
    '/area', '/region', '/province', '/city', '/district', '/street', '/address', '/addresses', '/location', '/geo', '/coordinates',
    '/org', '/orgs', '/organization', '/organizations', '/orgId', '/orgCode', '/dept', '/dept', '/departments', '/deptId', '/deptCode', '/company', '/companyInfo',
    '/category', '/categories', '/catalog', '/catalogs', '/type', '/types', '/kind', '/kinds', '/class', '/classes', '/classification', '/classify',
    '/tag', '/tags', '/label', '/labels', '/classify', '/group', '/groups', '/groupBy', '/groupId', '/groupName',
    '/attachment', '/attachments', '/file', '/files', '/document', '/documents', '/doc', '/docs', '/fileList', '/fileUpload', '/fileDownload',
    '/image', '/images', '/img', '/imgs', '/pictures', '/picture', '/photo', '/photos', '/avatar', '/thumbnail', '/thumbnails', '/uploadImage', '/uploadFile',
    '/video', '/videos', '/audio', '/media', '/uploads', '/resource', '/resources', '/upload', '/download', '/stream', '/preview',
    '/comment', '/comments', '/reply', '/replies', '/message', '/messages', '/msg', '/msgs', '/chat', '/chats', '/conversation', '/conversations',
    '/notice', '/notices', '/notification', '/notifications', '/notify', '/alert', '/alerts', '/announce', '/announcement', '/announcements', '/bulletin',
    '/news', '/article', '/articles', '/blog', '/blogs', '/post', '/posts', '/topic', '/topics', '/forum', '/forums', '/discussion', '/discussions',
    '/product', '/products', '/productList', '/productDetail', '/goods', '/item', '/items', '/itemList', '/sku', '/merchandise', '/merchandise',
    '/order', '/orders', '/orderList', '/orderDetail', '/orderId', '/orderNo', '/cart', '/carts', '/shop', '/store', '/stores', '/payment', '/payments', '/transaction', '/transactions', '/trans',
    '/invoice', '/invoices', '/refund', '/refunds', '/return', '/returns', '/exchange', '/exchanges', '/coupon', '/coupons', '/promo', '/promos', '/promotion', '/promotions', '/discount', '/discounts',
    '/workflow', '/workflows', '/process', '/processes', '/processId', '/processInstance', '/task', '/tasks', '/taskId', '/taskList', '/approve', '/approves', '/approval', '/approvals', '/reject', '/rejects', '/reject',
    '/schedule', '/schedules', '/calendar', '/calendars', '/booking', '/bookings', '/appointment', '/appointments', '/reservation', '/reservations', '/resourceId', '/resource',
    '/validate', '/validation', '/verify', '/verification', '/check', '/inspect', '/inspection', '/inspections', '/test', '/tests', '/testing', '/qc', '/quality',
    '/excel', '/pdf', '/csv', '/zip', '/tar', '/gz', '/archive', '/archives', '/backup', '/backups', '/restore', '/restores', '/recovery', '/recover',
    '/copy', '/move', '/rename', '/share', '/sharing', '/link', '/links', '/unlink', '/bind', '/binds', '/unbind', '/connect', '/disconnect',
    '/logininfo', '/loginlog', '/logoutinfo', '/online', '/onlineUsers', '/active', '/activeUsers', '/inactiveUsers', '/logout', '/session', '/sessions',
    '/build', '/compile', '/compile', '/deploy', '/deploys', '/deployment', '/deployments', '/publish', '/published', '/release', '/releases', '/version', '/versions', '/versionHistory',
    '/health', '/healthCheck', '/ping', '/echo', '/time', '/timestamp', '/serverTime', '/sysTime',
    '/monitor', '/monitoring', '/metrics', '/metric', '/performance', '/perf', '/stats', '/statistics',
    '/cache', '/caches', '/clearCache', '/refreshCache', '/redis', '/memcached',
    '/encrypt', '/decrypt', '/encryption', '/decryption', '/cipher', '/security', '/secret', '/secrets',
    '/callback', '/webhook', '/webhooks', '/notify', '/push', '/pushNotification', '/send',
    '/area', '/province', '/city', '/district', '/region', '/zone', '/zones',
    '/bank', '/banks', '/card', '/cards', '/account', '/accounts', '/balance', '/withdraw', '/deposit', '/transfer', '/transfers',
    '/loan', '/loans', '/credit', '/credits', '/investment', '/investments', '/fund', '/funds', '/stock', '/bonds', '/asset', '/assets',
    '/insurance', '/insurances', '/claim', '/claims', '/policy', '/policies', '/premium', '/underwriting',
    '/patient', '/patients', '/doctor', '/doctors', '/nurse', '/nurses', '/department', '/departments', '/hospital', '/hospitals', '/clinic', '/clinics',
    '/appointment', '/appointments', '/prescription', '/prescriptions', '/diagnosis', '/diagnoses', '/treatment', '/treatments', '/surgery', '/surgeries',
    '/medicalRecord', '/medicalRecords', '/lab', '/labs', '/examination', '/examinations', '/imaging', '/radiology', '/test', '/tests', '/result', '/results',
    '/drug', '/drugs', '/medicine', '/medicines', '/pharmacy', '/pharmacies', '/vaccine', '/vaccines',
    '/student', '/students', '/teacher', '/teachers', '/professor', '/professors', '/faculty', '/faculties', '/course', '/courses', '/class', '/classes',
    '/lesson', '/lessons', '/lecture', '/lectures', '/assignment', '/assignments', '/homework', '/exam', '/exams', '/quiz', '/quizzes',
    '/grade', '/grades', '/score', '/scores', '/transcript', '/transcripts', '/enrollment', '/enrollments', '/registration',
    '/schedule', '/schedules', '/attendance', '/presence', '/absence', '/library', '/libraries', '/book', '/books', '/journal', '/journals',
    '/member', '/members', '/vip', '/vips', '/memberLevel', '/memberPoints', '/points', '/credit', '/credits',
    '/device', '/devices', '/sensor', '/sensors', '/gateway', '/gateways', '/gateway', '/iot', '/mqtt', '/telemetry',
    '/plant', '/plants', '/station', '/stations', '/substation', '/substations', '/transformer', '/transformers', '/generator', '/generators',
    '/power', '/powers', '/grid', '/grids', '/network', '/networks', '/meter', '/meters', '/reading', '/readings',
    '/oil', '/gas', '/petroleum', '/refinery', '/pipeline', '/pipelines', '/tank', '/tanks', '/storage', '/storages',
    '/solar', '/wind', '/hydro', '/nuclear', '/renewable', '/energy', '/energies', '/production', '/capacity',
    '/shipment', '/shipments', '/package', '/packages', '/parcel', '/parcels', '/tracking', '/track', '/truck', '/trucks', '/fleet', '/fleets',
    '/driver', '/drivers', '/courier', '/couriers', '/express', '/freight', '/cargo', '/container', '/containers',
    '/flight', '/flights', '/airport', '/airports', '/vessel', '/vessels', '/voyage', '/voyages', '/port', '/ports',
    '/citizen', '/citizens', '/resident', '/residents', '/household', '/households', '/affair', '/affairs',
    '/approval', '/approvals', '/office', '/offices', '/bureau', '/bureaus', '/petition', '/petitions',
    '/proposal', '/proposals', '/feedback', '/suggestion', '/suggestions', '/emergency', '/emergencies', '/disaster', '/disasters',
    '/troop', '/troops', '/unit', '/units', '/mission', '/missions', '/operation', '/operations', '/intel', '/intelligence',
    '/equipment', '/weapons', '/supplies', '/logistics', '/communication', '/communications', '/briefing', '/briefings',
    '/player', '/players', '/avatar', '/avatars', '/guild', '/guilds', '/clan', '/clans', '/team', '/teams',
    '/quest', '/quests', '/dungeon', '/dungeons', '/boss', '/bosses', '/match', '/matches', '/leaderboard', '/rank', '/ranks',
    '/currency', '/currencies', '/coin', '/coins', '/gem', '/gems', '/shop', '/stores', '/deal', '/deals', '/offer', '/offers',
    '/ad', '/ads', '/advertising', '/impression', '/click', '/conversion'
]

FUZZ_SUFFIXES = [
    'List', 'ListJson', 'ListJsonData', 'ListData', 'ListAll', 'ListByPage', 'ListPage', 'ListById', 'ListByName', 'ListByStatus',
    'GetList', 'GetAll', 'GetPage', 'GetById', 'GetByCode', 'GetByName', 'GetInfo', 'GetDetail', 'GetDetailById', 'GetInfoById', 'GetOne', 'GetSingle',
    'Save', 'SaveOrUpdate', 'SaveAll', 'SaveBatch', 'Update', 'UpdateById', 'UpdateAll', 'UpdateBatch', 'UpdateStatus',
    'Add', 'AddBatch', 'AddAll', 'Create', 'CreateById', 'CreateAll', 'CreateBatch',
    'Delete', 'DeleteById', 'DeleteAll', 'DeleteBatch', 'Remove', 'RemoveById', 'RemoveAll', 'BatchDelete', 'BatchRemove', 'SoftDelete', 'SoftRemove',
    'JsonData', 'Json', 'JsonList', 'JsonById', 'TreeList', 'TreeData', 'Tree', 'TreeById', 'TreeNode', 'TreeNodes',
    'Select', 'SelectById', 'SelectAll', 'SelectPage', 'SelectList', 'Combo', 'ComboData', 'ComboBox', 'ComboList', 'ComboTree',
    'Option', 'Options', 'OptionList', 'OptionData', 'Autocomplete', 'Suggest', 'Suggestion', 'Suggestions', 'Lookup',
    'Export', 'ExportExcel', 'ExportCsv', 'ExportPdf', 'ExportData', 'ExportJson', 'ExportAll', 'Import', 'ImportExcel', 'ImportCsv', 'ImportData', 'ImportJson',
    'Download', 'DownloadExcel', 'DownloadPdf', 'DownloadFile', 'Upload', 'UploadFile', 'UploadImage', 'UploadExcel', 'UploadVideo',
    'Page', 'PageData', 'PageList', 'PageJson', 'PageInfo', 'Pagination', 'Paginate', 'Pager', 'PageSize', 'PageNum', 'PageNo',
    'Count', 'Total', 'Sum', 'Stat', 'Stats', 'Statistics', 'Summary', 'Analytics', 'CountByStatus', 'TotalByType',
    'Info', 'InfoById', 'Detail', 'Details', 'DetailById', 'View', 'ViewById', 'Show', 'ShowById', 'Fetch', 'FetchById', 'FetchAll', 'Load', 'LoadById', 'LoadAll', 'Get', 'GetById', 'GetAll', 'GetPage',
    'Login', 'Logout', 'Register', 'Signin', 'Signout', 'Signup', 'ResetPwd', 'ForgotPwd', 'ResetPassword', 'ForgotPassword', 'ChangePassword', 'ModifyPassword',
    'Auth', 'AuthById', 'Token', 'RefreshToken', 'AccessToken', 'Verify', 'Captcha', 'Validate', 'Validation', 'Verification', 'VerifyEmail', 'VerifyPhone',
    'Menu', 'Nav', 'NavMenu', 'Navigation', 'Sidebar', 'Routes', 'RouteList', 'RouteById', 'Permissions', 'PermissionList', 'PermissionById', 'Access', 'AccessList',
    'User', 'UserList', 'UserInfo', 'UserPage', 'UserDetail', 'UserById', 'UserByName', 'UserByDept', 'UserByRole', 'Profile', 'Account', 'Current', 'CurrentUser', 'Own',
    'Role', 'RoleList', 'RoleInfo', 'RoleById', 'RoleByName', 'RoleAll', 'Dept', 'DeptList', 'DeptInfo', 'DeptById', 'DeptByName', 'DeptAll', 'Org', 'OrgList', 'OrgInfo',
    'Product', 'ProductList', 'ProductInfo', 'ProductDetail', 'ProductById', 'ProductByName', 'ProductByCategory', 'ProductAll',
    'Order', 'OrderList', 'OrderInfo', 'OrderDetail', 'OrderById', 'OrderByNo', 'OrderByStatus', 'OrderAll',
    'Category', 'CategoryList', 'CategoryInfo', 'CategoryById', 'CategoryByName', 'CategoryAll', 'CategoryTree',
    'Config', 'ConfigList', 'ConfigInfo', 'ConfigById', 'ConfigByKey', 'ConfigAll', 'Settings', 'SettingsById', 'Dict', 'DictList', 'DictInfo', 'DictById', 'DictByType',
    'Enum', 'EnumList', 'EnumInfo', 'EnumById', 'EnumByType', 'EnumAll',
    'Log', 'LogList', 'LogPage', 'LogInfo', 'LogById', 'LogByType', 'LogAll', 'Audit', 'AuditList', 'AuditById', 'History', 'HistoryList', 'Record', 'RecordList', 'Records',
    'Article', 'ArticleList', 'ArticleInfo', 'ArticleDetail', 'ArticleById', 'ArticleByCategory', 'ArticleAll',
    'News', 'NewsList', 'NewsInfo', 'NewsDetail', 'NewsById', 'NewsAll',
    'Comment', 'CommentList', 'CommentInfo', 'CommentById', 'CommentByArticle', 'CommentAll',
    'File', 'FileList', 'FileInfo', 'FileById', 'FileByName', 'FileAll', 'Image', 'ImageList', 'ImageInfo', 'ImageById', 'ImageAll',
    'Video', 'VideoList', 'VideoInfo', 'VideoById', 'VideoAll', 'Notice', 'NoticeList', 'NoticeInfo', 'NoticeById', 'NoticeAll',
    'Notification', 'NotifyList', 'NotifyInfo', 'NotifyById', 'NotifyAll', 'Alert', 'AlertList', 'AlertInfo', 'AlertById', 'AlertAll',
    'Message', 'MsgList', 'MsgInfo', 'MsgById', 'MsgAll', 'MessageList', 'MessageInfo', 'MessageById', 'MessageAll',
    'Search', 'SearchById', 'SearchByName', 'SearchByKeyword', 'SearchAll', 'Query', 'QueryById', 'QueryByName', 'QueryByCondition', 'QueryAll',
    'Filter', 'FilterById', 'FilterByStatus', 'FilterAll', 'Sort', 'SortById', 'SortByOrder', 'SortAll', 'Order', 'OrderById', 'OrderByTime',
    'Enable', 'EnableById', 'Disable', 'DisableById', 'Toggle', 'ToggleById', 'Status', 'StatusById', 'State', 'StateById', 'Check', 'CheckById', 'Verify', 'VerifyById',
    'Submit', 'SubmitById', 'Reset', 'ResetById', 'Init', 'InitById', 'Initialize', 'InitializeById', 'Refresh', 'RefreshById', 'Reload', 'ReloadById', 'Sync', 'SyncById', 'Merge', 'MergeById',
    'Approve', 'ApproveById', 'ApproveAll', 'Reject', 'RejectById', 'RejectAll', 'Process', 'ProcessById', 'ProcessAll', 'Task', 'TaskList', 'TaskById', 'TaskAll',
    'Schedule', 'ScheduleById', 'ScheduleAll', 'Booking', 'BookingById', 'BookingAll', 'Appointment', 'AppointmentById', 'AppointmentAll',
    'Customer', 'CustomerList', 'CustomerInfo', 'CustomerById', 'CustomerByName', 'CustomerAll',
    'Supplier', 'SupplierList', 'SupplierInfo', 'SupplierById', 'SupplierAll',
    'Employee', 'EmployeeList', 'EmployeeInfo', 'EmployeeById', 'EmployeeByDept', 'EmployeeAll',
    'Member', 'MemberList', 'MemberInfo', 'MemberById', 'MemberByLevel', 'MemberAll',
    'Partner', 'PartnerList', 'PartnerInfo', 'PartnerById', 'PartnerAll',
    'Admin', 'AdminList', 'AdminInfo', 'AdminById', 'AdminAll',
    'Batch', 'BatchById', 'BatchAll', 'BatchCreate', 'BatchUpdate', 'BatchDelete',
    'All', 'AllList', 'AllById', 'AllByStatus', 'AllData', 'AllInfo', 'AllDetail', 'AllRecords', 'AllLogs', 'AllUsers', 'AllProducts', 'AllOrders'
]

PATH_FRAGMENTS = [
    'user', 'users', 'userinfo', 'userlist', 'userpage', 'profile', 'account', 'accounts', 'currentUser', 'currentuser',
    'order', 'orders', 'orderdetail', 'orderlist', 'orderInfo', 'orderAll', 'cart', 'carts', 'payment', 'payments', 'transaction', 'transactions',
    'product', 'products', 'productlist', 'productInfo', 'productDetail', 'goods', 'item', 'items', 'itemlist', 'sku', 'merchandise',
    'role', 'roles', 'roleInfo', 'roleList', 'permission', 'permissions', 'perm', 'perms', 'menu', 'menus', 'resource', 'resources', 'menuInfo',
    'dept', 'depts', 'department', 'departments', 'deptInfo', 'deptList', 'org', 'orgs', 'organization', 'organizations', 'orgInfo', 'orgList', 'company', 'companies',
    'category', 'categories', 'categorylist', 'categoryInfo', 'catalog', 'catalogs', 'tag', 'tags', 'label', 'labels', 'group', 'groups', 'groupList',
    'config', 'configs', 'configuration', 'configInfo', 'configList', 'settings', 'setting', 'dict', 'dicts', 'dictionary', 'dictInfo', 'dictList',
    'admin', 'admins', 'adminUser', 'adminUsers', 'system', 'systemConfig', 'systemInfo', 'auth', 'authInfo', 'login', 'logout', 'register', 'signup', 'captcha', 'validcode', 'verification',
    'api', 'apis', 'v1', 'v2', 'v3', 'v4', 'v5', 'rest', 'soap', 'graphql', 'rpc', 'gateway', 'openapi', 'swagger',
    'file', 'files', 'fileInfo', 'fileList', 'fileUpload', 'fileDownload', 'document', 'documents', 'doc', 'docs', 'attachment', 'attachments',
    'image', 'images', 'imageInfo', 'imageList', 'img', 'imgs', 'picture', 'pictures', 'photo', 'photos', 'avatar', 'thumbnail', 'thumbnails',
    'video', 'videos', 'videoInfo', 'videoList', 'audio', 'audios', 'media', 'medias', 'upload', 'uploads', 'download', 'downloads', 'stream', 'preview',
    'article', 'articles', 'articleInfo', 'articleList', 'articleDetail', 'news', 'newss', 'newsInfo', 'newsList', 'blog', 'blogs', 'blogInfo', 'post', 'posts', 'postList', 'topic', 'topics', 'topicList', 'comment', 'comments', 'commentList',
    'notice', 'notices', 'noticeInfo', 'noticeList', 'notification', 'notifications', 'notifyList', 'message', 'messages', 'msg', 'msgs', 'chat', 'chats',
    'workflow', 'workflows', 'workflowInfo', 'process', 'processes', 'processInfo', 'processList', 'task', 'tasks', 'taskInfo', 'taskList', 'schedule', 'schedules', 'calendar', 'calendars', 'booking', 'bookings',
    'area', 'areas', 'region', 'regions', 'province', 'provinces', 'city', 'cities', 'district', 'districts', 'street', 'streets', 'address', 'addresses', 'location', 'locations', 'geo', 'zone', 'zones',
    'log', 'logs', 'logInfo', 'logList', 'logging', 'audit', 'audits', 'auditInfo', 'history', 'record', 'records', 'recordList', 'track', 'tracking', 'trail', 'trace', 'debug', 'loginLog', 'operationLog', 'accessLog', 'errorLog',
    'stat', 'stats', 'statistics', 'statInfo', 'analytics', 'report', 'reports', 'reportInfo', 'reportList', 'summary', 'dashboard', 'dashboards',
    'customer', 'customers', 'customerInfo', 'customerList', 'supplier', 'suppliers', 'supplierInfo', 'supplierList', 'employee', 'employees', 'employeeInfo', 'employeeList', 'member', 'members', 'memberInfo', 'memberList', 'partner', 'partners', 'partnerInfo',
    'invoice', 'invoices', 'invoiceInfo', 'invoiceList', 'refund', 'refunds', 'return', 'returns', 'exchange', 'exchanges', 'coupon', 'coupons', 'promo', 'promos', 'promotion', 'promotions', 'discount', 'discounts',
    'backup', 'backups', 'backupInfo', 'restore', 'restores', 'export', 'exports', 'exportInfo', 'import', 'imports', 'importInfo', 'migrate', 'migration', 'transfer', 'transfers',
    'dashboard', 'dashboards', 'home', 'index', 'main', 'workspace', 'console', 'welcome', 'portal', 'page',
    'bank', 'banks', 'bankInfo', 'card', 'cards', 'cardInfo', 'balance', 'withdraw', 'withdraws', 'deposit', 'deposits', 'transfer', 'transfers', 'exchange', 'exchanges',
    'loan', 'loans', 'loanInfo', 'credit', 'credits', 'creditInfo', 'investment', 'investments', 'fund', 'funds', 'fundInfo', 'stock', 'bonds', 'asset', 'assets', 'assetInfo', 'portfolio', 'portfolios',
    'insurance', 'insurances', 'insuranceInfo', 'claim', 'claims', 'claimInfo', 'policy', 'policies', 'policyInfo', 'premium', 'underwriting',
    'patient', 'patients', 'patientInfo', 'patientList', 'doctor', 'doctors', 'doctorInfo', 'nurse', 'nurses', 'nurseInfo', 'hospital', 'hospitals', 'hospitalInfo', 'clinic', 'clinics', 'clinicInfo',
    'appointment', 'appointments', 'appointmentInfo', 'prescription', 'prescriptions', 'prescriptionInfo', 'diagnosis', 'diagnoses', 'diagnosisInfo', 'treatment', 'treatments', 'treatmentInfo', 'surgery', 'surgeries', 'surgeryInfo',
    'medicalRecord', 'medicalRecords', 'medicalRecordInfo', 'lab', 'labs', 'labInfo', 'examination', 'examinations', 'examInfo', 'imaging', 'radiology', 'test', 'tests', 'testInfo', 'result', 'results', 'resultInfo',
    'drug', 'drugs', 'drugInfo', 'medicine', 'medicines', 'medicineInfo', 'pharmacy', 'pharmacies', 'pharmacyInfo', 'vaccine', 'vaccines', 'vaccineInfo',
    'student', 'students', 'studentInfo', 'studentList', 'teacher', 'teachers', 'teacherInfo', 'professor', 'professors', 'professorInfo', 'faculty', 'faculties', 'facultyInfo',
    'course', 'courses', 'courseInfo', 'courseList', 'class', 'classes', 'classInfo', 'lesson', 'lessons', 'lessonInfo', 'lecture', 'lectures', 'lectureInfo', 'assignment', 'assignments', 'assignmentInfo', 'homework', 'exam', 'exams', 'examInfo', 'quiz', 'quizzes', 'quizInfo',
    'grade', 'grades', 'gradeInfo', 'score', 'scores', 'scoreInfo', 'transcript', 'transcripts', 'transcriptInfo', 'enrollment', 'enrollments', 'enrollmentInfo', 'registration', 'registrations',
    'library', 'libraries', 'libraryInfo', 'book', 'books', 'bookInfo', 'journal', 'journals', 'journalInfo', 'publication', 'publications',
    'member', 'members', 'memberLevel', 'memberPoints', 'points', 'vip', 'vips', 'vipInfo',
    'device', 'devices', 'deviceInfo', 'deviceList', 'sensor', 'sensors', 'sensorInfo', 'gateway', 'gateways', 'gatewayInfo', 'iot', 'telemetry', 'telemetryInfo',
    'plant', 'plants', 'plantInfo', 'station', 'stations', 'stationInfo', 'substation', 'substations', 'substationInfo', 'transformer', 'transformers', 'transformerInfo', 'generator', 'generators', 'generatorInfo',
    'power', 'powers', 'powerInfo', 'grid', 'grids', 'gridInfo', 'network', 'networks', 'networkInfo', 'meter', 'meters', 'meterInfo', 'reading', 'readings', 'readingInfo',
    'oil', 'gas', 'petroleum', 'refinery', 'refineries', 'pipeline', 'pipelines', 'tank', 'tanks', 'storage', 'storages',
    'solar', 'solarInfo', 'wind', 'windInfo', 'hydro', 'hydroInfo', 'nuclear', 'nuclearInfo', 'renewable', 'energy', 'energies', 'energyInfo', 'production', 'capacity',
    'shipment', 'shipments', 'shipmentInfo', 'package', 'packages', 'packageInfo', 'parcel', 'parcels', 'parcelInfo', 'tracking', 'track', 'truck', 'trucks', 'truckInfo', 'fleet', 'fleets', 'fleetInfo',
    'driver', 'drivers', 'driverInfo', 'courier', 'couriers', 'courierInfo', 'express', 'freight', 'cargo', 'container', 'containers', 'containerInfo',
    'flight', 'flights', 'flightInfo', 'airport', 'airports', 'airportInfo', 'vessel', 'vessels', 'vesselInfo', 'voyage', 'voyages', 'voyageInfo', 'port', 'ports', 'portInfo',
    'citizen', 'citizens', 'citizenInfo', 'resident', 'residents', 'residentInfo', 'household', 'households', 'householdInfo', 'affair', 'affairs', 'affairInfo',
    'approval', 'approvals', 'approvalInfo', 'office', 'offices', 'officeInfo', 'bureau', 'bureaus', 'bureauInfo', 'petition', 'petitions', 'petitionInfo',
    'proposal', 'proposals', 'proposalInfo', 'feedback', 'suggestion', 'suggestions', 'emergency', 'emergencies', 'emergencyInfo', 'disaster', 'disasters', 'disasterInfo',
    'troop', 'troops', 'unit', 'units', 'mission', 'missions', 'operation', 'operations', 'intel', 'intelligence',
    'equipment', 'weapons', 'supplies', 'logistics', 'communication', 'communications', 'briefing', 'briefings',
    'player', 'players', 'avatar', 'avatars', 'guild', 'guilds', 'clan', 'clans', 'team', 'teams',
    'quest', 'quests', 'dungeon', 'dungeons', 'boss', 'bosses', 'match', 'matches', 'leaderboard', 'rank', 'ranks',
    'currency', 'currencies', 'coin', 'coins', 'gem', 'gems', 'shop', 'stores', 'deal', 'deals', 'offer', 'offers',
    'ad', 'ads', 'advertising', 'impression', 'impressions', 'click', 'clicks', 'conversion', 'conversions'
]
