"""
探测相关词表配置
包含 ACTION_SUFFIXES、RESOURCE_WORDS、CRUD_SUFFIXES 等
从 engine.py 迁移而来
"""

ACTION_SUFFIXES = {
    'login', 'logout', 'register', 'signup', 'signin', 'signout', 'forgot', 'reset', 'resetpwd', 'forgotpwd',
    'verify', 'validate', 'confirm', 'authorize', 'authentication', 'authenticate',
    'oauth', 'sso', 'token', 'refresh', 'revoke', 'jwt', 'cas', 'saml',
    'search', 'query', 'suggest', 'autocomplete', 'lookup', 'find', 'filter', 'browse',
    'sort', 'order', 'page', 'paginate', 'list', 'lists', 'getlist', 'getall', 'getpage',
    'hot', 'trending', 'recommend', 'recommendation', 'related', 'similar', 'popular',
    'export', 'import', 'download', 'upload', 'batch', 'sync', 'synchronize', 'transfer',
    'backup', 'restore', 'migrate', 'clone', 'duplicate', 'replicate', 'archive',
    'subscribe', 'unsubscribe', 'follow', 'unfollow', 'like', 'unlike', 'favorite', 'bookmark',
    'share', 'comment', 'forward', 'reply', 'discuss', 'collaborate',
    'pay', 'payment', 'refund', 'cancel', 'close', 'checkout', 'status', 'history', 'transaction',
    'enable', 'disable', 'activate', 'deactivate', 'lock', 'unlock', 'freeze', 'unfreeze',
    'open', 'start', 'stop', 'pause', 'resume', 'reset', 'reboot', 'shutdown',
    'submit', 'approve', 'reject', 'accept', 'deny', 'admit', 'discharge',
    'settings', 'preference', 'options', 'setup', 'init', 'initialize', 'permission', 'configure', 'config',
    'detail', 'info', 'information', 'profile', 'view', 'read', 'fetch', 'load', 'get', 'retrieve',
    'add', 'create', 'edit', 'update', 'modify', 'patch', 'put', 'delete', 'remove',
    'set', 'save', 'store', 'persist', 'commit', 'rollback',
    'stat', 'stats', 'statistics', 'report', 'reports', 'summary', 'total', 'count', 'sum', 'analytics', 'metric', 'metrics',
    'callback', 'notify', 'notice', 'notification', 'alert', 'alerts', 'alarm', 'alarms', 'push', 'pull', 'message', 'send',
    'image', 'images', 'video', 'videos', 'audio', 'file', 'files', 'document', 'documents', 'avatar', 'thumbnail', 'stream', 'media',
    'location', 'map', 'geo', 'geolocation', 'nearby', 'distance', 'route', 'gps', 'coordinate', 'lat', 'lng', 'position',
    'call', 'dial', 'hangup', 'answer', 'transfer', 'conference', 'voip',
    'check', 'inspect', 'examine', 'test', 'trial', 'simulate', 'preview',
    'deploy', 'publish', 'release', 'build', 'compile', 'package',
    'track', 'trace', 'monitor', 'observe', 'watch', 'surveillance', 'recon',
    'manage', 'control', 'operate', 'dispatch', 'schedule', 'plan',
    'enroll', 'register', 'admit', 'appointment', 'booking', 'reserve', 'reservation', 'queue',
    'prescribe', 'diagnose', 'treat', 'therapy', 'cure',
    'charge', 'fee', 'cost', 'price', 'quote', 'estimate', 'calculate', 'compute',
    'claim', 'insure', 'underwrite', 'assess', 'evaluate',
    'produce', 'manufacture', 'assembly', 'fabricate', 'quality', 'qc',
    'calibrate', 'maintain', 'repair', 'service', 'spare',
    'disarm', 'engage', 'combat', 'mission', 'tactic', 'strategic', 'command', 'evacuate',
    'grade', 'score', 'evaluate', 'quiz', 'exam', 'examine',
    'readwrite', 'execute', 'run', 'process',
    'investigate', 'analyze', 'study', 'survey', 'probe', 'scan',
    'graduate', 'scholarship', 'tuition',
    'allocate', 'distribute', 'supply', 'procure', 'purchase',
    'match', 'matchmake', 'matchmaking', 'rank', 'leaderboard', 'rating',
    'browse', 'advertise', 'advertising', 'impression', 'click', 'conversion',
    'brighten', 'dim', 'turn_on', 'turn_off', 'toggle', 'automate', 'scene', 'trigger', 'action',
    'ota', 'firmware', 'upgrade', 'patch', 'hotfix',
    'deposit', 'withdraw', 'balance', 'exchange', 'recharge', 'bind', 'unbind',
    'dispense', 'refer', 'admission', 'consult', 'followup', 'administer', 'record', 'print',
    'present', 'absent', 'hand_in', 'drop', 'waive', 'exempt', 'remind', 'attend',
    'complete', 'progress', 'handle', 'apply', 'announce', 'address', 'measure', 'aggregate',
    'classify', 'brief', 'debrief', 'decode', 'encrypt', 'standby', 'surrender', 'disengage',
    'optimize', 'identify', 'discover', 'forecast', 'shipping', 'discount', 'promotion',
    'commission', 'exercise', 'transmit', 'locate', 'receive', 'leave', 'join', 'invite', 'mark',
    'default', 'method', 'secure', 'assign',
    'quality_check', 'acknowledge', 'clear', 'collect', 'certificate', 'excuse', 'timer', 'pair',
    'reward', 'gift', 'evolve', 'trade', 'ready', 'train', 'drill', 'equip', 'refuel', 'encode', 'decrypt',
    'review', 'select', 'rate', 'redeem', 'coupon', 'wechat', 'alipay', 'card', 'cart', 'return', 'pickup', 'deliver',
    'play', 'end', 'quit', 'ban', 'mute', 'kick', 'admin', 'active', 'arm'
}

RESOURCE_WORDS = {
    'user', 'users', 'account', 'accounts', 'order', 'orders', 'product', 'products',
    'item', 'items', 'admin', 'auth', 'token', 'role', 'roles', 'permission', 'permissions',
    'menu', 'menus', 'config', 'configuration', 'system', 'log', 'logs', 'monitor', 'tool', 'tools',
    'file', 'files', 'document', 'documents', 'folder', 'folders',
    'category', 'categories', 'catalog', 'catalogs', 'tag', 'tags', 'label', 'labels',
    'article', 'articles', 'post', 'posts', 'blog', 'blogs', 'news', 'comment', 'comments',
    'customer', 'customers', 'client', 'clients', 'employee', 'employees', 'member', 'members',
    'payment', 'payments', 'transaction', 'transactions', 'invoice', 'invoices', 'receipt', 'receipts',
    'address', 'addresses', 'notification', 'notifications', 'message', 'messages', 'msg',
    'device', 'devices', 'gateway', 'gateways', 'sensor', 'sensors', 'alarm', 'alarms', 'rule', 'rules',
    'warehouse', 'warehouses', 'delivery', 'deliveries', 'driver', 'drivers', 'vehicle', 'vehicles',
    'route', 'routes', 'server', 'servers', 'cluster', 'clusters', 'node', 'nodes',
    'guild', 'guilds', 'clan', 'clans', 'team', 'teams', 'party', 'parties',
    'patient', 'patients', 'doctor', 'doctors', 'nurse', 'nurses', 'department', 'departments', 'hospital', 'hospitals',
    'appointment', 'appointments', 'prescription', 'prescriptions', 'diagnosis', 'diagnoses',
    'treatment', 'treatments', 'surgery', 'surgeries', 'drug', 'drugs', 'medicine', 'medicines',
    'vaccine', 'vaccines', 'lab', 'labs', 'clinic', 'clinics', 'pharmacy', 'pharmacies',
    'student', 'students', 'teacher', 'teachers', 'professor', 'professors', 'faculty', 'faculties',
    'course', 'courses', 'class', 'classes', 'lesson', 'lessons', 'lecture', 'lectures',
    'assignment', 'assignments', 'homework', 'exam', 'exams', 'quiz', 'quizzes',
    'grade', 'grades', 'score', 'scores', 'transcript', 'transcripts',
    'enrollment', 'enrollments', 'registration', 'schedule', 'schedules',
    'attendance', 'presence', 'absence', 'leave', 'vacation',
    'major', 'majors', 'school', 'schools', 'college', 'colleges', 'university', 'universities',
    'library', 'libraries', 'book', 'books', 'journal', 'journals', 'publication', 'publications',
    'resource', 'resources', 'material', 'materials', 'content', 'contents', 'discussion', 'discussions', 'forum', 'forums',
    'parent', 'parents', 'guardian', 'guardians', 'family', 'families',
    'fee', 'fees', 'scholarship', 'scholarships', 'diploma', 'diplomas', 'degree', 'degrees',
    'shipment', 'shipments', 'package', 'packages', 'parcel', 'parcels', 'truck', 'trucks', 'fleet', 'fleets',
    'waypoint', 'waypoints', 'destination', 'destinations', 'tracking', 'pickup', 'pickups',
    'courier', 'couriers', 'express', 'standard', 'freight', 'cargo',
    'container', 'containers', 'airline', 'airlines', 'flight', 'flights', 'airport', 'airports',
    'port', 'ports', 'shipping', 'vessel', 'vessels', 'voyage', 'voyages', 'booking', 'reservations', 'ticket', 'tickets',
    'shop', 'shops', 'store', 'stores', 'cart', 'carts', 'wishlist', 'wishlists',
    'vip', 'vips', 'brand', 'brands', 'promotion', 'promotions', 'discount', 'discounts', 'coupon', 'coupons',
    'inventory', 'inventories', 'stock', 'stocks', 'supplier', 'suppliers', 'purchase', 'purchases', 'procurement',
    'review', 'reviews', 'rating', 'ratings', 'recommendations', 'similar',
    'thing', 'things', 'hub', 'hubs', 'controller', 'controllers',
    'home', 'homes', 'room', 'rooms', 'scene', 'scenes', 'automation',
    'camera', 'cameras', 'doorbell', 'doorbells', 'lock', 'locks',
    'light', 'lights', 'switch', 'switches', 'outlet', 'outlets',
    'thermostat', 'thermostats', 'ac', 'heater', 'humidifier', 'purifier',
    'tv', 'television', 'speaker', 'speakers', 'display', 'displays',
    'firmware', 'ota', 'update', 'updates', 'data', 'datas', 'telemetry', 'analytics',
    'rule', 'rules', 'trigger', 'triggers',
    'player', 'players', 'avatar', 'avatars', 'inventory', 'inventories',
    'equipment', 'skills', 'skill', 'level', 'levels', 'exp', 'experience',
    'mission', 'missions', 'quest', 'quests', 'dungeon', 'dungeons', 'boss', 'bosses',
    'match', 'matches', 'matchmaking', 'leaderboard', 'rank', 'ranks', 'rating',
    'currency', 'currencies', 'coin', 'coins', 'gem', 'gems', 'cash',
    'deal', 'deals', 'offer', 'offers', 'ad', 'ads', 'advertising', 'impression', 'click', 'conversion',
    'channel', 'channels', 'anti_cheat',
    'ledger', 'ledger', 'budget', 'budgets', 'cost', 'costs', 'expense', 'expenses',
    'revenue', 'revenues', 'profit', 'profits', 'margin', 'tax', 'taxes', 'invoice', 'invoices',
    'statement', 'statements', 'reconciliation', 'clearing', 'settlement',
    'compliance', 'aml', 'kyc', 'fraud', 'risk', 'audit', 'audits',
    'merchants', 'merchant', 'pos', 'atmp', 'branch', 'branches', 'teller',
    'underwriting', 'claim', 'claims', 'policy', 'policies', 'premium', 'insurer',
    'exchange', 'currency', 'rate', 'rates', 'interest', 'credit', 'debit',
    'investment', 'fund', 'funds', 'stock', 'bonds', 'asset', 'assets', 'portfolio',
    'gateway', 'api', 'apis', 'v1', 'v2', 'v3', 'v4', 'rest', 'soap', 'graphql', 'rpc', 'svc', 'service',
    'ws', 'websocket', 'mqtt', 'coap', 'edge', 'fog',
    'open', 'public', 'internal', 'external', 'secure', 'encrypted',
    'cards', 'card', 'bond', 'bonds', 'insurance', 'balance', 'loans', 'loan', 'deposits', 'deposit',
    'withdraw', 'withdrawals', 'transfers', 'transfer',
    'imaging', 'radiology', 'examination', 'examinations', 'anesthesia', 'specimen', 'recovery',
    'batch', 'batches', 'defect', 'defects', 'workorder', 'workorders', 'process', 'processes',
    'machines', 'machine', 'alerts', 'alert', 'events', 'event', 'parameter', 'parameters', 'actuator', 'actuators',
    'search', 'plans', 'plan', 'domains', 'domain', 'workspace', 'workspaces', 'project', 'projects',
    'integration', 'integrations', 'secrets', 'secret', 'dns',
    'records', 'record', 'archives', 'archive', 'regulations', 'supervision', 'statistics', 'stat',
    'dashboard', 'dashboards', 'inspection',
    'command', 'commands', 'corps',
    'medical_record', 'medical_records', 'result', 'results', 'pacs', 'ward', 'wards', 'health',
    'feed', 'feeds', 'setting', 'settings', 'subscriptions', 'subscription', 'webhook', 'webhooks', 'profile', 'profiles',
    'certs', 'ssl', 'oauth', 'keys', 'key',
    'recipe', 'recipes', 'rework', 'quality', 'robot', 'robots', 'plc', 'plcs', 'line', 'lines',
    'receivers', 'receiver', 'sender', 'senders', 'history', 'track', 'status',
    'sku', 'goods', 'price', 'prices', 'chain', 'merchandise', 'recommend', 'related',
    'tokens', 'token', 'friends', 'friend'
}

CRUD_SUFFIXES = {
    'list', 'detail', 'add', 'create', 'edit', 'update', 'delete', 'remove',
    'get', 'set', 'info', 'profile', 'settings', 'config', 'index',
    'search', 'query', 'fetch', 'load', 'save', 'submit'
}
