"""
Export Module
导出模块 - 支持多种格式
"""

import json
import os
import logging
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field
from datetime import datetime
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment

logger = logging.getLogger(__name__)


@dataclass
class ExportConfig:
    """导出配置"""
    format: str = "json"
    output_dir: str = "./results"
    include_responses: bool = True
    include_vulnerabilities: bool = True
    include_sensitive: bool = True
    openapi_version: str = "3.0.3"


class OpenAPIExporter:
    """OpenAPI 格式导出器"""
    
    def __init__(self, config: Optional[ExportConfig] = None):
        self.config = config or ExportConfig()
    
    def export(
        self,
        apis: List[Dict],
        target: str,
        output_path: str
    ) -> bool:
        """导出为 OpenAPI 格式"""
        try:
            spec = self._build_openapi_spec(apis, target)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(spec, f, ensure_ascii=False, indent=2)
            
            return True
        except Exception as e:
            logger.error(f"OpenAPI export error: {e}")
            return False
    
    def _build_openapi_spec(self, apis: List[Dict], target: str) -> Dict:
        """构建 OpenAPI 规范"""
        parsed = self._parse_target(target)
        
        spec = {
            "openapi": self.config.openapi_version,
            "info": {
                "title": f"API Security Scan - {parsed.get('domain', target)}",
                "description": "Auto-generated by ApiRed Scanner",
                "version": "1.0.0",
                "generated": datetime.now().isoformat()
            },
            "servers": [
                {"url": f"{parsed.get('scheme', 'https')}://{parsed.get('netloc', target)}"}
            ],
            "paths": {}
        }
        
        for api in apis:
            path = api.get('path', '')
            if not path:
                continue
            
            if path not in spec["paths"]:
                spec["paths"][path] = {}
            
            method = api.get('method', 'get').lower()
            
            spec["paths"][path][method] = {
                "summary": api.get('title', f"API endpoint: {path}"),
                "description": api.get('description', ''),
                "tags": api.get('tags', []),
                "parameters": self._build_parameters(api),
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "content": {
                            "application/json": {
                                "schema": api.get('response_schema', {})
                            }
                        }
                    }
                },
                "security": api.get('security', [])
            }
        
        return spec
    
    def _parse_target(self, target: str) -> Dict:
        """解析目标 URL"""
        from urllib.parse import urlparse
        try:
            parsed = urlparse(target)
            return {
                'scheme': parsed.scheme,
                'netloc': parsed.netloc,
                'domain': parsed.netloc.split(':')[0] if parsed.netloc else target
            }
        except (ValueError, Exception) as e:
            logger.debug(f"Target parse error: {e}")
            return {'scheme': 'https', 'netloc': target, 'domain': target}
    
    def _build_parameters(self, api: Dict) -> List[Dict]:
        """构建参数"""
        params = []
        parameters = api.get('parameters', [])
        
        for param in parameters:
            params.append({
                "name": param.get('name', ''),
                "in": param.get('in', 'query'),
                "required": param.get('required', False),
                "schema": {
                    "type": param.get('type', 'string')
                },
                "description": param.get('description', '')
            })
        
        return params 


class CSVExporter:
    """CSV 格式导出器
    参考 URLFinder 的 CSV 导出格式
    """

    def export(self, data: Dict, output_path: str) -> bool:
        """导出为 CSV 格式"""
        try:
            lines = []

            lines.extend(self._export_summary_csv(data))
            lines.append("")
            lines.extend(self._export_apis_csv(data))
            lines.append("")
            lines.extend(self._export_vulnerabilities_csv(data))
            lines.append("")
            lines.extend(self._export_sensitive_csv(data))

            with open(output_path, 'w', encoding='utf-8-sig', newline='') as f:
                f.write('\n'.join(lines))

            return True
        except Exception as e:
            logger.error(f"CSV export error: {e}")
            return False

    def _export_summary_csv(self, data: Dict) -> List[str]:
        """导出摘要为 CSV"""
        lines = ["# ApiRed Scan Summary"]

        summary = data.get('summary', {})
        lines.append(f"Target,{data.get('target_url', '')}")
        lines.append(f"Scan Time,{data.get('start_time', '')}")
        lines.append(f"Duration,{data.get('duration', 0):.2f}s")
        lines.append("")
        lines.append("# API Statistics")
        lines.append(f"Total APIs,{summary.get('total_apis', 0)}")
        lines.append(f"Alive APIs,{summary.get('alive_apis', 0)}")
        lines.append(f"High Value APIs,{summary.get('high_value_apis', 0)}")
        lines.append(f"Vulnerabilities,{len(data.get('vulnerabilities', []))}")
        lines.append(f"Sensitive Data,{len(data.get('sensitive_data', []))}")

        return lines

    def _export_apis_csv(self, data: Dict) -> List[str]:
        """导出 API 列表为 CSV"""
        lines = ["# API Endpoints"]

        headers = ["URL", "Method", "Status", "Score", "Service", "Tags", "Source"]
        lines.append(','.join(headers))

        apis = data.get('api_endpoints', [])
        for api in apis:
            row = [
                self._escape_csv(api.get('full_url', api.get('path', ''))),
                api.get('method', 'GET'),
                str(api.get('status', '')),
                str(api.get('score', 0)),
                self._escape_csv(api.get('service_key', '')),
                self._escape_csv(', '.join(api.get('tags', []))),
                api.get('source', '')
            ]
            lines.append(','.join(row))

        return lines

    def _export_vulnerabilities_csv(self, data: Dict) -> List[str]:
        """导出漏洞为 CSV"""
        lines = ["# Vulnerabilities"]

        headers = ["Type", "Severity", "URL", "Method", "Evidence", "Payload", "Remediation"]
        lines.append(','.join(headers))

        vulns = data.get('vulnerabilities', [])
        for vuln in vulns:
            row = [
                self._escape_csv(vuln.get('vuln_type', '')),
                self._escape_csv(vuln.get('severity', '')),
                self._escape_csv(vuln.get('url', '')),
                vuln.get('method', ''),
                self._escape_csv(vuln.get('evidence', '')[:200]),
                self._escape_csv(vuln.get('payload', '')[:100]),
                self._escape_csv(vuln.get('remediation', '')[:200])
            ]
            lines.append(','.join(row))

        return lines

    def _export_sensitive_csv(self, data: Dict) -> List[str]:
        """导出敏感信息为 CSV"""
        lines = ["# Sensitive Data"]

        headers = ["Type", "Severity", "URL", "Content Type", "Matched Rule", "Context"]
        lines.append(','.join(headers))

        sensitive = data.get('sensitive_data', [])
        for item in sensitive:
            row = [
                self._escape_csv(item.get('data_type', item.get('type', ''))),
                self._escape_csv(item.get('severity', '')),
                self._escape_csv(item.get('location', item.get('url', ''))),
                self._escape_csv(item.get('content_type', '')),
                self._escape_csv(item.get('rule_name', '')),
                self._escape_csv(item.get('context', '')[:200])
            ]
            lines.append(','.join(row))

        return lines

    def _escape_csv(self, value: str) -> str:
        """转义 CSV 值"""
        if not value:
            return ''
        value = str(value)
        if any(c in value for c in [',', '"', '\n', '\r']):
            return '"' + value.replace('"', '""') + '"'
        return value


class JSONExporter:
    """JSON 格式导出器"""
    
    def export(self, data: Dict, output_path: str) -> bool:
        """导出为 JSON"""
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            return True
        except Exception as e:
            logger.error(f"JSON export error: {e}")
            return False


class ExcelExporter:
    """Excel 格式导出器"""
    
    def __init__(self):
        self.header_font = Font(bold=True, color="FFFFFF")
        self.header_fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
        self.alignment = Alignment(horizontal="left", vertical="center")
    
    def export(self, data: Dict, output_path: str) -> bool:
        """导出为 Excel 多 Sheet"""
        try:
            wb = openpyxl.Workbook()
            wb.remove(wb.active)
            
            self._create_summary_sheet(wb, data)
            self._create_apis_sheet(wb, data)
            self._create_vulns_sheet(wb, data)
            self._create_sensitive_sheet(wb, data)
            
            wb.save(output_path)
            return True
        except Exception as e:
            logger.error(f"Excel export error: {e}")
            return False
    
    def _create_summary_sheet(self, wb, data: Dict):
        """创建摘要 Sheet"""
        ws = wb.create_sheet("Summary")
        
        summary = data.get('summary', {})
        
        rows = [
            ("Target", data.get('target_url', '')),
            ("Scan Time", data.get('start_time', '')),
            ("Duration", f"{data.get('duration', 0):.2f}s"),
            ("", ""),
            ("API Statistics", ""),
            ("Total APIs", summary.get('total_apis', 0)),
            ("Alive APIs", summary.get('alive_apis', 0)),
            ("High Value APIs", summary.get('high_value_apis', 0)),
            ("", ""),
            ("Security Findings", ""),
            ("Vulnerabilities", len(data.get('vulnerabilities', []))),
            ("Sensitive Data", len(data.get('sensitive_data', []))),
        ]
        
        for row_idx, (label, value) in enumerate(rows, 1):
            ws.cell(row=row_idx, column=1, value=label)
            ws.cell(row=row_idx, column=2, value=value)
    
    def _create_apis_sheet(self, wb, data: Dict):
        """创建 API 列表 Sheet"""
        ws = wb.create_sheet("APIs")
        
        headers = ["Path", "Method", "Status", "Score", "Service", "Tags"]
        
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=header)
            cell.font = self.header_font
            cell.fill = self.header_fill
        
        apis = data.get('api_endpoints', [])
        for row_idx, api in enumerate(apis, 2):
            ws.cell(row=row_idx, column=1, value=api.get('path', ''))
            ws.cell(row=row_idx, column=2, value=api.get('method', 'GET'))
            ws.cell(row=row_idx, column=3, value=api.get('status', ''))
            ws.cell(row=row_idx, column=4, value=api.get('score', 0))
            ws.cell(row=row_idx, column=5, value=api.get('service_key', ''))
            ws.cell(row=row_idx, column=6, value=', '.join(api.get('tags', [])))
    
    def _create_vulns_sheet(self, wb, data: Dict):
        """创建漏洞 Sheet"""
        ws = wb.create_sheet("Vulnerabilities")
        
        headers = ["Type", "Severity", "API", "Evidence", "Remediation"]
        
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=header)
            cell.font = self.header_font
            cell.fill = self.header_fill
        
        vulns = data.get('vulnerabilities', [])
        for row_idx, vuln in enumerate(vulns, 2):
            ws.cell(row=row_idx, column=1, value=vuln.get('vuln_type', ''))
            ws.cell(row=row_idx, column=2, value=vuln.get('severity', ''))
            ws.cell(row=row_idx, column=3, value=vuln.get('api_id', ''))
            ws.cell(row=row_idx, column=4, value=vuln.get('evidence', '')[:100])
            ws.cell(row=row_idx, column=5, value=vuln.get('remediation', '')[:100])
    
    def _create_sensitive_sheet(self, wb, data: Dict):
        """创建敏感信息 Sheet"""
        ws = wb.create_sheet("Sensitive Data")
        
        headers = ["Type", "Severity", "Location", "Context"]
        
        for col, header in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=header)
            cell.font = self.header_font
            cell.fill = self.header_fill
        
        sensitive = data.get('sensitive_data', [])
        for row_idx, item in enumerate(sensitive, 2):
            ws.cell(row=row_idx, column=1, value=item.get('data_type', ''))
            ws.cell(row=row_idx, column=2, value=item.get('severity', ''))
            ws.cell(row=row_idx, column=3, value=item.get('location', ''))
            ws.cell(row=row_idx, column=4, value=item.get('context', '')[:100])


class HTMLReporter:
    """HTML 报告生成器"""
    
    TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ApiRed Scan Report - {target}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }}
        .header h1 {{ margin: 0 0 10px 0; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin-bottom: 20px; }}
        .stat-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .stat-card .value {{ font-size: 2em; font-weight: bold; color: #667eea; }}
        .stat-card .label {{ color: #666; margin-top: 5px; }}
        .section {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); margin-bottom: 20px; }}
        .section h2 {{ margin-top: 0; color: #333; border-bottom: 2px solid #667eea; padding-bottom: 10px; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th {{ background: #667eea; color: white; padding: 12px; text-align: left; }}
        td {{ padding: 10px; border-bottom: 1px solid #eee; }}
        tr:hover {{ background: #f8f8f8; }}
        .badge {{ display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }}
        .badge-critical {{ background: #dc3545; color: white; }}
        .badge-high {{ background: #fd7e14; color: white; }}
        .badge-medium {{ background: #ffc107; color: black; }}
        .badge-low {{ background: #28a745; color: white; }}
        .api-path {{ font-family: monospace; background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
        .method {{ font-weight: bold; padding: 2px 6px; border-radius: 3px; }}
        .method-get {{ background: #61affe; color: white; }}
        .method-post {{ background: #49cc90; color: white; }}
        .method-put {{ background: #fca130; color: white; }}
        .method-delete {{ background: #f93e3e; color: white; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>ApiRed Security Scan Report</h1>
            <p>Target: {target} | Time: {scan_time} | Duration: {duration}s</p>
        </div>
        
        <div class="stats">
            <div class="stat-card">
                <div class="value">{total_apis}</div>
                <div class="label">Total APIs</div>
            </div>
            <div class="stat-card">
                <div class="value">{alive_apis}</div>
                <div class="label">Alive APIs</div>
            </div>
            <div class="stat-card">
                <div class="value">{vuln_count}</div>
                <div class="label">Vulnerabilities</div>
            </div>
            <div class="stat-card">
                <div class="value">{sensitive_count}</div>
                <div class="label">Sensitive Data</div>
            </div>
        </div>
        
        <div class="section">
            <h2>High Risk APIs</h2>
            <table>
                <thead>
                    <tr>
                        <th>API</th>
                        <th>Method</th>
                        <th>Score</th>
                        <th>Risk</th>
                    </tr>
                </thead>
                <tbody>
                    {high_risk_rows}
                </tbody>
            </table>
        </div>
        
        <div class="section">
            <h2>Vulnerabilities</h2>
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Severity</th>
                        <th>API</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {vuln_rows}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>
"""
    
    def export(self, data: Dict, output_path: str) -> bool:
        """导出为 HTML 报告"""
        try:
            html = self._render_template(data)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html)
            
            return True
        except Exception as e:
            logger.error(f"HTML export error: {e}")
            return False
    
    def _render_template(self, data: Dict) -> str:
        """渲染模板"""
        summary = data.get('summary', {})
        apis = data.get('api_endpoints', [])[:20]
        vulns = data.get('vulnerabilities', [])
        
        high_risk_rows = []
        for api in apis:
            if api.get('score', 0) >= 7:
                high_risk_rows.append(f"""
                <tr>
                    <td><span class="api-path">{api.get('path', '')}</span></td>
                    <td><span class="method method-{api.get('method', 'get').lower()}">{api.get('method', 'GET')}</span></td>
                    <td>{api.get('score', 0)}</td>
                    <td><span class="badge badge-high">High</span></td>
                </tr>
                """)
        
        vuln_rows = []
        for vuln in vulns[:20]:
            severity = vuln.get('severity', 'medium').lower()
            badge_class = f"badge-{severity}"
            vuln_rows.append(f"""
            <tr>
                <td>{vuln.get('vuln_type', '')}</td>
                <td><span class="badge {badge_class}">{vuln.get('severity', '')}</span></td>
                <td><span class="api-path">{vuln.get('api_id', '')}</span></td>
                <td>{vuln.get('title', '')[:50]}</td>
            </tr>
            """)
        
        return self.TEMPLATE.format(
            target=data.get('target_url', ''),
            scan_time=data.get('start_time', ''),
            duration=f"{data.get('duration', 0):.2f}",
            total_apis=summary.get('total_apis', 0),
            alive_apis=summary.get('alive_apis', 0),
            vuln_count=len(vulns),
            sensitive_count=len(data.get('sensitive_data', [])),
            high_risk_rows='\n'.join(high_risk_rows) or '<tr><td colspan="4">No high risk APIs found</td></tr>',
            vuln_rows='\n'.join(vuln_rows) or '<tr><td colspan="4">No vulnerabilities found</td></tr>'
        )


class FLUXHtmlReporter:
    """FLUX 增强 HTML 报告生成器"""
    
    FLUX_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ApiRed FLUX 增强安全扫描报告</title>
    <style>
        :root {{
            --primary: #667eea;
            --secondary: #764ba2;
            --critical: #dc3545;
            --high: #fd7e14;
            --medium: #ffc107;
            --low: #28a745;
            --info: #17a2b8;
        }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1400px; margin: 0 auto; }}
        .header {{ background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 20px; }}
        .header h1 {{ margin: 0 0 10px 0; font-size: 1.8em; }}
        .header .subtitle {{ opacity: 0.8; font-size: 0.9em; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 15px; margin-bottom: 20px; }}
        .stat-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); text-align: center; }}
        .stat-card .value {{ font-size: 2.2em; font-weight: bold; color: var(--primary); }}
        .stat-card .label {{ color: #666; margin-top: 5px; font-size: 0.85em; }}
        .stat-card.highlight {{ background: linear-gradient(135deg, var(--primary), var(--secondary)); }}
        .stat-card.highlight .value, .stat-card.highlight .label {{ color: white; }}
        .section {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); margin-bottom: 20px; }}
        .section h2 {{ margin-top: 0; color: #333; border-bottom: 2px solid var(--primary); padding-bottom: 10px; font-size: 1.2em; }}
        .section h3 {{ color: #555; margin-bottom: 10px; font-size: 1em; }}
        .subsection {{ background: #f8f9fa; padding: 15px; border-radius: 6px; margin-bottom: 15px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 10px; }}
        th {{ background: var(--primary); color: white; padding: 10px; text-align: left; font-weight: 500; }}
        td {{ padding: 8px 10px; border-bottom: 1px solid #eee; }}
        tr:hover {{ background: #f8f8f8; }}
        tr.highlight {{ background: #fff3cd; }}
        .badge {{ display: inline-block; padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }}
        .badge-critical {{ background: var(--critical); color: white; }}
        .badge-high {{ background: var(--high); color: white; }}
        .badge-medium {{ background: var(--medium); color: black; }}
        .badge-low {{ background: var(--low); color: white; }}
        .badge-info {{ background: var(--info); color: white; }}
        .api-path {{ font-family: 'Consolas', monospace; background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }}
        .method {{ font-weight: bold; padding: 2px 6px; border-radius: 3px; font-size: 0.8em; }}
        .method-get {{ background: #61affe; color: white; }}
        .method-post {{ background: #49cc90; color: white; }}
        .method-put {{ background: #fca130; color: white; }}
        .method-delete {{ background: #f93e3e; color: white; }}
        .waf-alert {{ background: linear-gradient(135deg, #ff6b6b, #ee5a5a); color: white; padding: 15px; border-radius: 8px; margin-bottom: 15px; }}
        .waf-alert h4 {{ margin: 0 0 5px 0; }}
        .fingerprint-tag {{ display: inline-block; background: #e9ecef; padding: 4px 10px; border-radius: 20px; margin: 3px; font-size: 0.85em; }}
        .fingerprint-tag.ai {{ background: #d4edda; color: #155724; }}
        .fingerprint-tag.framework {{ background: #cce5ff; color: #004085; }}
        .fingerprint-tag.waf {{ background: #f8d7da; color: #721c24; }}
        .fusion-stats {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 15px; }}
        .fusion-stat {{ background: #f8f9fa; padding: 10px; border-radius: 6px; text-align: center; }}
        .fusion-stat .value {{ font-size: 1.5em; font-weight: bold; color: var(--primary); }}
        .fusion-stat .label {{ font-size: 0.8em; color: #666; }}
        .priority-bar {{ display: flex; align-items: center; margin: 5px 0; }}
        .priority-bar .bar {{ flex: 1; height: 8px; background: #e9ecef; border-radius: 4px; overflow: hidden; }}
        .priority-bar .fill {{ height: 100%; border-radius: 4px; }}
        .priority-bar .fill.critical {{ background: var(--critical); }}
        .priority-bar .fill.high {{ background: var(--high); }}
        .priority-bar .fill.medium {{ background: var(--medium); }}
        .priority-bar .fill.low {{ background: var(--low); }}
        .empty-state {{ text-align: center; padding: 30px; color: #999; }}
        .grid-2 {{ display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>ApiRed FLUX 增强安全扫描报告</h1>
            <div class="subtitle">目标: {target} | 时间: {scan_time} | 耗时: {duration}s</div>
        </div>
        
        <div class="stats">
            <div class="stat-card highlight">
                <div class="value">{total_apis}</div>
                <div class="label">发现端点</div>
            </div>
            <div class="stat-card">
                <div class="value">{fusion_high}</div>
                <div class="label">高置信度</div>
            </div>
            <div class="stat-card">
                <div class="value">{fusion_runtime}</div>
                <div class="label">运行时确认</div>
            </div>
            <div class="stat-card">
                <div class="value">{vuln_count}</div>
                <div class="label">漏洞</div>
            </div>
            <div class="stat-card">
                <div class="value">{sensitive_count}</div>
                <div class="label">敏感信息</div>
            </div>
            <div class="stat-card">
                <div class="value">{fingerprint_count}</div>
                <div class="label">指纹识别</div>
            </div>
        </div>
        
        {waf_alert}
        
        <div class="section">
            <h2>端点融合统计</h2>
            <div class="fusion-stats">
                <div class="fusion-stat">
                    <div class="value">{fusion_total}</div>
                    <div class="label">融合后总数</div>
                </div>
                <div class="fusion-stat">
                    <div class="value">{fusion_api}</div>
                    <div class="label">API端点</div>
                </div>
                <div class="fusion-stat">
                    <div class="value">{fusion_admin}</div>
                    <div class="label">管理后台</div>
                </div>
                <div class="fusion-stat">
                    <div class="value">{fusion_ai}</div>
                    <div class="label">AI接口</div>
                </div>
            </div>
        </div>
        
        <div class="section">
            <h2>指纹识别结果</h2>
            {fingerprint_section}
        </div>
        
        <div class="grid-2">
            <div class="section">
                <h2>漏洞优先级排序</h2>
                {priority_section}
            </div>
            
            <div class="section">
                <h2>敏感信息检测 (FLUX)</h2>
                {sensitive_section}
            </div>
        </div>
        
        <div class="section">
            <h2>FLUX 安全检测</h2>
            {flux_security_section}
        </div>
        
        <div class="section">
            <h2>高置信度端点</h2>
            {high_confidence_section}
        </div>
    </div>
</body>
</html>
"""

    def export(self, data: Dict, output_path: str) -> bool:
        """导出为 FLUX 增强 HTML 报告"""
        try:
            html = self._render_flux_template(data)
            os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html)
            return True
        except Exception as e:
            logger.error(f"FLUX HTML export error: {e}")
            return False
    
    def _render_flux_template(self, data: Dict) -> str:
        flux = data.get('flux_enhanced', {})
        
        fusion_data = flux.get('fusion_endpoints', {})
        fusion_stats = fusion_data.get('stats', {})
        by_type = fusion_stats.get('by_type', {})
        
        fingerprint_section = self._render_fingerprints(flux.get('fingerprints', []))
        priority_section = self._render_priority(flux.get('prioritized_vulns', []))
        sensitive_section = self._render_sensitive(flux.get('sensitive_data', []))
        flux_security_section = self._render_flux_security(flux)
        high_conf_section = self._render_high_confidence(fusion_data.get('high_confidence_endpoints', []))
        
        waf_detected = flux.get('waf_detected')
        waf_alert = ''
        if waf_detected:
            waf_alert = f'''
            <div class="waf-alert">
                <h4>WAF 检测警告</h4>
                <p>检测到 Web 应用防火墙: <strong>{waf_detected}</strong>，部分绕过技术可能失效</p>
            </div>'''
        
        fp_count = len(flux.get('fingerprints', []))
        
        return self.FLUX_TEMPLATE.format(
            target=data.get('target_url', ''),
            scan_time=data.get('start_time', ''),
            duration=f"{data.get('duration', 0):.2f}",
            total_apis=data.get('summary', {}).get('total_apis', data.get('total_apis', 0)),
            fusion_high=fusion_stats.get('high_confidence', 0),
            fusion_runtime=fusion_stats.get('runtime_confirmed', 0),
            vuln_count=len(data.get('vulnerabilities', [])),
            sensitive_count=len(flux.get('sensitive_data', [])),
            fingerprint_count=fp_count,
            waf_alert=waf_alert or '<div class="section"><h2>WAF 检测</h2><div class="empty-state">未检测到 WAF</div></div>',
            fusion_total=fusion_stats.get('after_fusion', 0),
            fusion_api=by_type.get('api_endpoint', 0),
            fusion_admin=by_type.get('admin_panel', 0),
            fusion_ai=by_type.get('ai_interface', 0),
            fingerprint_section=fingerprint_section,
            priority_section=priority_section,
            sensitive_section=sensitive_section,
            flux_security_section=flux_security_section,
            high_confidence_section=high_conf_section,
        )
    
    def _render_fingerprints(self, fingerprints: List) -> str:
        if not fingerprints:
            return '<div class="empty-state">未发现指纹</div>'
        
        html = '<div class="subsection">'
        categories = {}
        for fp in fingerprints[:30]:
            cat = fp.get('category', 'Other')
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(fp)
        
        for cat, items in categories.items():
            cat_class = 'ai' if 'ai' in cat.lower() else ('waf' if 'waf' in cat.lower() else ('framework' if any(fw in cat.lower() for fw in ['framework', 'cms', 'server']) else ''))
            html += f'<h3>{cat}</h3><div>'
            for item in items[:10]:
                name = item.get('name', 'Unknown')
                confidence = item.get('confidence', 0)
                html += f'<span class="fingerprint-tag {cat_class}">{name} ({confidence}%)</span>'
            html += '</div>'
        
        html += '</div>'
        return html
    
    def _render_priority(self, vulns: List) -> str:
        if not vulns:
            return '<div class="empty-state">无优先级漏洞</div>'
        
        priority_counts = {'critical': 0, 'high': 0, 'medium': 0, 'low': 0}
        for v in vulns:
            p = v.get('priority', 'medium').lower()
            priority_counts[p] = priority_counts.get(p, 0) + 1
        
        total = sum(priority_counts.values()) or 1
        html = ''
        for level in ['critical', 'high', 'medium', 'low']:
            count = priority_counts.get(level, 0)
            pct = int(count / total * 100)
            html += f'''
            <div class="priority-bar">
                <span class="badge badge-{level}" style="width:70px">{level.upper()}</span>
                <div class="bar"><div class="fill {level}" style="width:{pct}%"></div></div>
                <span style="width:50px;text-align:right">{count}</span>
            </div>'''
        
        html += '<table><tr><th>类型</th><th>URL</th><th>评分</th></tr>'
        for v in vulns[:5]:
            html += f'''<tr class="highlight">
                <td><span class="badge badge-{v.get('priority', 'medium').lower()}">{v.get('vuln_type', '')}</span></td>
                <td><span class="api-path">{v.get('url', '')[:50]}</span></td>
                <td>{v.get('total_score', 0):.2f}</td>
            </tr>'''
        html += '</table>'
        return html
    
    def _render_sensitive(self, items: List) -> str:
        if not items:
            return '<div class="empty-state">未发现敏感信息</div>'
        
        html = '<table><tr><th>类型</th><th>掩码值</th><th>来源</th></tr>'
        for item in items[:10]:
            masked = item.get('masked_value', item.get('evidence', ''))[:30]
            html += f'''<tr>
                <td><span class="badge badge-critical">{item.get('type', item.get('data_type', 'unknown'))}</span></td>
                <td><code>{masked}</code></td>
                <td><span class="api-path">{item.get('source', item.get('location', ''))[:40]}</span></td>
            </tr>'''
        html += '</table>'
        return html
    
    def _render_flux_security(self, flux: Dict) -> str:
        sections = []
        
        ai = flux.get('ai_security', [])
        if ai:
            sections.append(f'<div class="subsection"><h3>AI 安全 ({len(ai)}项)</h3>')
            for item in ai[:5]:
                sections.append(f'<div>- {item.get("component", "")}: {item.get("vuln_type", "")}</div>')
            sections.append('</div>')
        
        k8s = flux.get('k8s_security', [])
        if k8s:
            sections.append(f'<div class="subsection"><h3>K8s 安全 ({len(k8s)}项)</h3>')
            for item in k8s[:5]:
                sections.append(f'<div>- {item.get("component", "")}: {item.get("vuln_type", "")}</div>')
            sections.append('</div>')
        
        container = flux.get('container_security', [])
        if container:
            sections.append(f'<div class="subsection"><h3>容器安全 ({len(container)}项)</h3>')
            for item in container[:5]:
                sections.append(f'<div>- {item.get("runtime", "")}: {item.get("vuln_type", "")}</div>')
            sections.append('</div>')
        
        cicd = flux.get('cicd_security', [])
        if cicd:
            sections.append(f'<div class="subsection"><h3>CI/CD 安全 ({len(cicd)}项)</h3>')
            for item in cicd[:5]:
                sections.append(f'<div>- {item.get("component", "")}: {item.get("vuln_type", "")}</div>')
            sections.append('</div>')
        
        cloud = flux.get('cloud_security', [])
        if cloud:
            sections.append(f'<div class="subsection"><h3>云安全 ({len(cloud)}项)</h3>')
            for item in cloud[:5]:
                sections.append(f'<div>- {item.get("vuln_type", "")}: {item.get("detail", "")[:50]}</div>')
            sections.append('</div>')
        
        if not sections:
            return '<div class="empty-state">未发现 FLUX 安全问题</div>'
        
        return '\n'.join(sections)
    
    def _render_high_confidence(self, endpoints: List) -> str:
        if not endpoints:
            return '<div class="empty-state">无高置信度端点</div>'
        
        html = '<table><tr><th>端点</th><th>类型</th><th>置信度</th><th>证据数</th></tr>'
        for ep in endpoints[:10]:
            conf = ep.get('confidence_score', 0)
            conf_pct = int(conf * 100)
            html += f'''<tr>
                <td><span class="api-path">{ep.get('full_url', ep.get('url', ''))[:60]}</span></td>
                <td><span class="badge badge-info">{ep.get('endpoint_type', 'unknown')}</span></td>
                <td>
                    <div class="priority-bar">
                        <div class="bar"><div class="fill {'high' if conf > 0.7 else 'medium'}" style="width:{conf_pct}%"></div></div>
                        <span>{conf_pct}%</span>
                    </div>
                </td>
                <td>{ep.get('evidence_count', 0)}</td>
            </tr>'''
        html += '</table>'
        return html


class JUnitExporter:
    """JUnit XML 格式导出器"""
    
    def export(self, scan_result: Dict, output_path: str) -> bool:
        """导出为 JUnit XML 格式"""
        try:
            os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
            
            test_cases = self._build_test_cases(scan_result)
            xml_content = self._generate_junit_xml(scan_result, test_cases)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(xml_content)
            
            return True
        except Exception as e:
            logger.error(f"JUnit export error: {e}")
            return False
    
    def _build_test_cases(self, scan_result: Dict) -> List[Dict]:
        """构建测试用例"""
        test_cases = []
        
        vulns = scan_result.get('vulnerabilities', [])
        for vuln in vulns:
            test_cases.append({
                'classname': f"security.{vuln.get('vuln_type', 'unknown')}",
                'name': f"{vuln.get('api_id', 'unknown')}_{vuln.get('vuln_type', 'unknown')}",
                'failure': True,
                'message': vuln.get('title', ''),
                'severity': vuln.get('severity', 'medium')
            })
        
        sensitive = scan_result.get('sensitive_data', [])
        for item in sensitive:
            test_cases.append({
                'classname': f"sensitive.{item.get('data_type', 'unknown')}",
                'name': f"{item.get('location', 'unknown')}_{item.get('data_type', 'unknown')}",
                'failure': True,
                'message': item.get('context', ''),
                'severity': item.get('severity', 'medium')
            })
        
        return test_cases
    
    def _generate_junit_xml(self, scan_result: Dict, test_cases: List[Dict]) -> str:
        """生成 JUnit XML 格式"""
        total = len(test_cases) + scan_result.get('summary', {}).get('total_apis', 0)
        failures = len(test_cases)
        
        xml_lines = [
            '<?xml version="1.0" encoding="UTF-8"?>',
            '<testsuites>',
            f'  <testsuite name="ApiRed Security Scan" tests="{total}" failures="{failures}" errors="0" skipped="0">',
            f'    <testcase classname="scan.summary" name="scan_target" time="{scan_result.get("duration", 0):.3f}"/>'
        ]
        
        for tc in test_cases:
            severity_esc = self._escape_xml(tc.get('severity', ''))
            message_esc = self._escape_xml(tc.get('message', ''))
            
            xml_lines.append(
                f'    <testcase classname="{tc["classname"]}" name="{tc["name"]}">'
            )
            xml_lines.append(
                f'      <failure message="{message_esc}" type="{severity_esc}">'
            )
            xml_lines.append(
                f'        <![CDATA[{tc.get("message", "")}]]>'
            )
            xml_lines.append('      </failure>')
            xml_lines.append('    </testcase>')
        
        xml_lines.extend([
            '  </testsuite>',
            '</testsuites>'
        ])
        
        return '\n'.join(xml_lines)
    
    def _escape_xml(self, text: str) -> str:
        """转义 XML 特殊字符"""
        if not text:
            return ''
        return (text
                .replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;')
                .replace("'", '&apos;'))


class ReportExporter:
    """统一报告导出器"""
    
    def __init__(self, output_dir: str = "./results"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        
        self.exporters = {
            'openapi': OpenAPIExporter(),
            'json': JSONExporter(),
            'excel': ExcelExporter(),
            'csv': CSVExporter(),
            'html': HTMLReporter(),
            'junit': JUnitExporter()
        }
    
    def export(
        self,
        scan_result: Dict,
        target: str,
        formats: Optional[List[str]] = None
    ) -> Dict[str, str]:
        """导出多种格式报告"""
        formats = formats or ['json', 'html']
        results = {}
        
        target_folder = target.replace('://', '_').replace('/', '_').replace('.', '_')
        target_dir = os.path.join(self.output_dir, target_folder)
        os.makedirs(target_dir, exist_ok=True)
        
        for fmt in formats:
            if fmt not in self.exporters:
                continue
            
            try:
                filename = f"report.{fmt}"
                output_path = os.path.join(target_dir, filename)
                
                if fmt == 'openapi':
                    success = self.exporters[fmt].export(
                        scan_result.get('api_endpoints', []),
                        target,
                        output_path
                    )
                else:
                    success = self.exporters[fmt].export(scan_result, output_path)
                
                if success:
                    results[fmt] = output_path
            except Exception as e:
                logger.error(f"Export {fmt} failed: {e}")
        
        return results
